<div class="col-sm-12">
    <div class="row">
        <!-- Jumbotron Header -->
        <header class="jumbotron hero-spacer">
            <h1>User Bloqué !</h1>
            <p>Vous êtes actuellement bloqué. Vérifier la charte du site : <a href="/charte" target="_blank">ici</a></p>
            <p>Si vous avez des questions, veuillez nous contacter à l'adresse suivante : <A HREF="mailto:crowdfundingwavre@gmail.com">crowdfunding-wavrien@gmail.com</A></p>

        </header>
    </div>
</div>

<script src="/dist/js/disconnect.js"></script>
