<div class="col-xs-12 col-md-10 col-md-offset-1">
    <div class="list-group">
        <a href="#" class="list-group-item list-group-item-success list-button-add" data-toggle="modal" data-target="#modalCreateGranted">Ajouter</a>
        <li class="list-group-item"> </li>
        <li class="list-group-item list-group-item-success active">Modérateurs</li>
        <?php
            foreach ($users as $user)
            {
                if($user->getRole() == "ROLE_MODO")
                    echo '<a href="#" class="list-group-item list-button-show" data-id="'.$user->getId().'" data-username="'.$user->getUsername().'" data-role="'.$user->getRole().'">'.$user->getUsername().'</a>';
            }
        ?>
        <li class="list-group-item"> </li>
        <li class="list-group-item list-group-item-success active">Administrateurs</li>
        <?php
            foreach ($users as $user)
            {
                if($user->getRole() == "ROLE_ADMIN" && $user->getUsername() != $_SESSION["user"]->getUsername())
                    echo '<a href="#" class="list-group-item list-button-show" data-id="'.$user->getId().'" data-username="'.$user->getUsername().'" data-role="'.$user->getRole().'">'.$user->getUsername().'</a>';
            }
        ?>
    </div>
</div>

<!-- Modal granted edit. -->
<div class="modal fade" id="modalEditGranted" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h5 class="modal-title">Modification de <span id="grantedUsername"></span></h5>
            </div>
            <div class="modal-body">
                <form id="formEditGranted">
                    <div class="form-group">
                        <label for="profileUsername">Rôle</label>
                        <select class="form-control" name="role" id="roleEdit">
                            <option value="ROLE_ADMIN">Administrateur</option>
                            <option value="ROLE_MODO">Modérateur</option>
                        </select>
                        <input type="hidden" name="id" class="form-control" id="grantedId">
                        <input type="hidden" name="username" class="form-control" id="grantedUsernameForm">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" id="buttonGrantedDelete">Supprimer</button>
                <button type="button" class="btn btn-success" id="buttonGrantedSave">Sauvegarder</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal category creation. -->
<div class="modal fade" id="modalCreateGranted" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h5 class="modal-title" id="registerModalLabel">Nouveau rôle</h5>
            </div>
            <div class="modal-body">
                <form id="formCreateGranted">
                    <div class="form-group">
                        <label for="grantedCreateUsername">Nom d'utilisateur</label>
                        <input type="text" name="username" class="form-control" id="grantedCreateUsername" placeholder="Nom d'utilisateur">
                    </div>
                    <div class="form-group">
                        <label for="grantedCreateUsername">Rôle</label>
                        <select class="form-control" name="role">
                            <option value="ROLE_ADMIN">Administrateur</option>
                            <option value="ROLE_MODO">Modérateur</option>
                        </select>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" id="buttonCreateGranted">Créer</button>
            </div>
        </div>
    </div>
</div>
<script src="/dist/js/granted.js"></script>
