<div class="col-xs-12 col-md-10 col-md-offset-1">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Nom d'utilisateur</th>
                <th>Commentaire</th>
                <th>Nombre de signalement</th>
                <th>Dernier signalement par</th>
            </tr>
        </thead>
        <tbody>
            <?php
                foreach ($reports as $report){
                    echo '<tr data-comment-id="'.$report->getComment()->getId().'" data-username="'.$report->getComment()->getUser()->getUsername().'" data-id="'.$report->getId().'" data-comment="'.$report->getComment()->getContent().'">';
                    echo '<th scope="row">'.$report->getComment()->getUser()->getUsername().'</th>';
                    echo '<td>'.$report->getComment()->getContent().'</td>';
                    echo '<td>'.$report->getAmount().'</td>';
                    echo '<td>'.$report->getUser()->getUsername().'</td>';
                    echo '</tr>';
                }
            ?>
         </tbody>
     </table>
</div>

<!-- Modal comment report details. -->
<div class="modal fade" id="modalModerateComment" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h5 class="modal-title" id="registerModalLabel">Modération de commentaire</h5>
            </div>
            <div class="modal-body">
                <div class="panel panel-default">
                    <div class="panel-heading" id="modalUsername"></div>
                    <div class="panel-body" id="modalComment">
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-warning btn-sm" id="buttonDelete">Supprimer le commentaire</button>
                <button type="button" class="btn btn-danger btn-sm" id="buttonBlock">Bloquer l'utilisateur</button>
                <button type="button" class="btn btn-success btn-sm" id="buttonDismiss">Laisser le commentaire</button>
            </div>
        </div>
    </div>
</div>
<script src="/dist/js/commentReport.js"></script>
