<div class="tab-pane" id="add-comment">
    <div class="form-group">
        
        <div class="col-sm-12">
            <textarea class="form-control" name="addComment" data-id="<?php echo $project->getId(); ?>" id="addComment" rows="5"></textarea>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-1 col-sm-10">
            <br>
            <button class="btn btn-success btn-circle" type="button" id="submitComment"><span class="glyphicon glyphicon-send"></span> Envoyer le commentaire</button>
        </div>
    </div>
</div>
