<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Identifiez-vous<span class="caret"></span></a>
    <ul class="dropdown-menu">
        <li><a href="" data-toggle="modal" data-target="#loginModal">Connexion</a></li>
        <li role="separator" class="divider"></li>
        <li><a href="" data-toggle="modal" data-target="#registerModal">Enregistrement</a></li>
    </ul>
</li>
