<div class="row">
    <div class="col-sm-10 col-sm-offset-1">
        <h2>CrowdFundin' se veut une plateforme de financement participatif liés à Wavre. Il faut donc impérativement que votre projet y soit lié.</h2>

        <ol>
            <li>
                <h3>CrowdFundin' favorise les campagnes qui:</h3>

                <ul>
                    <li>créent des produits ou services ayant une utilité sociale.</li>
                    <li>Ont un impact positif sur la création d’emploi.</li>
                    <li>Sont pionnières et innovantes.</li>
                </ul>
            </li>

            <li>
                <h3>Les campagnes doivent respecter:</h3>

                <ul>
                    <li>Les législations et régulations en vigueur.</li>
                    <li>Les règles éthiques et de gouvernance généralement admises.</li>
                    <li>L’environnement et les principes de précaution concernant les problèmes environnementaux.</li>
                    <li>Les droits de l’homme des personnes affectées par les activités de la campagne.</li>
                    <li>Les droits des consommsateurs.</li>
                </ul>
            </li>

            <li>
                <h3>Les campagnes ne peuvent en aucun cas être liées aux domaines suivants:</h3>

                <ul>
                    <li>Armes.</li>
                    <li>Drogues.</li>
                    <li>Prostitution.</li>
                    <li>Pornographie.</li>
                    <li>Trafic d’êtres humains ou d’organes.</li>
                    <li>En général, des produits ou services illégaux ou illicites.</li>
                </ul>
            </li>

        </ol>
        CrowdFundin' ne peut pas garantir que les campagnes respecteront toutes ces valeurs, c'est pourquoi nous comptons sur la communauté pour signaler les projets ne respectant pas ces points. Ne donnez pas d'étoiles à de tels projets car celles-ci ne seront pas remboursées.
    </div>
</div>
