<div class="col-xs-12 col-md-6 col-md-offset-3">
    <form id="formProfileEdit">

         <div class="imgcontainer">
            <img src="<?php echo $_SESSION["user"]->getAvatar(); ?>" alt="Avatar" class="avatar" id="avatar">
             <input type="hidden" name="MAX_FILE_SIZE" value="1048576" />
             <input type="file" class="input-file" name="new_avatar" id="new_avatar" /><br />
          </div>
        <div class="form-group">
            <label for="profileUsername">Nom d'utilisateur</label>
            <input type="text" name="username" class="form-control" id="profileUsername" aria-describedby="emailHelp" placeholder="Nom d'utilisateur"
            value="<?php echo $_SESSION["user"]->getUsername(); ?>" disabled>
        </div>
        <input name="username" type="hidden" value="<?php echo $_SESSION["user"]->getUsername(); ?>">
        <div class="form-group">
            <label for="registerLastname">Nom</label>
            <input type="text" name="lastname" class="form-control" id="registerLastname" aria-describedby="emailHelp"
            value="<?php echo $_SESSION["user"]->getLastname(); ?>">
        </div>
        <div class="form-group">
            <label for="registerFirstname">Prénom</label>
            <input type="text" name="firstname" class="form-control" id="registerFirstname" aria-describedby="emailHelp"
            value="<?php echo $_SESSION["user"]->getFirstname(); ?>">
        </div>
        <div class="form-group">
            <label for="registerEmail">Email</label>
            <input type="text" name="email" class="form-control" id="registerEmail" aria-describedby="emailHelp"
            value="<?php echo $_SESSION["user"]->getEmail(); ?>" disabled>
            <input type="hidden" name="email" class="form-control" id="registerEmail" aria-describedby="emailHelp"
            value="<?php echo $_SESSION["user"]->getEmail(); ?>" >
        </div>
         <a class="btn btn-primary" href="/password">Changer votre mot de passe</a>
        <button type="button" class="btn btn-success" id="buttonEditProfile">Valider</button>

    </form>
</div>

 <!-- sca : ajout informations pour la changement de mot de passe  -->

 <div class="modal fade" id="response-message" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header modal-header-success">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h1><i class="glyphicon glyphicon-info-sign"></i> <div id="getMessage"></div></h1>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Fermer</button>
            </div>
        </div>
    </div>
</div>
<script src="/dist/js/sha512.js"></script>
<script src="/dist/js/profile.js"></script>
