<div class="col-xs-12 col-md-6 col-md-offset-3">
    <form id="formProfileEditPassword">

         <div class="imgcontainer">
            <img src="<?php echo $_SESSION["user"]->getAvatar(); ?>" alt="Avatar" class="avatar">
          </div>
        <div class="form-group">
            <label for="profileUsername">Nom d'utilisateur</label>
            <input type="text" name="username" class="form-control" id="profileUsername" aria-describedby="emailHelp" placeholder="Nom d'utilisateur" 
            value="<?php echo $_SESSION["user"]->getUsername(); ?>" disabled>
        </div>
        <input name="username" type="hidden" value="<?php echo $_SESSION["user"]->getUsername(); ?>">
        <div class="form-group">
            <label for="profilePassword">Mot de passe</label>
            <input type="password" class="form-control" id="profilePassword" placeholder="Password">
            <input type="hidden" name="password" class="form-control" id="profileEncodedPassword" placeholder="Nouveau mot de passe">
        </div>
        <div class="form-group">
            <label for="profilePasswordConfirm">Mot de passe (confirmation)</label>
            <input type="password" class="form-control" id="profilePasswordConfirm" placeholder="Confirmer le nouveau mot de passe">
        </div>
         <a class="btn btn-primary" href="/profil">Retour</a>
        <button type="button" class="btn btn-success" id="buttonEditProfilePassword">Valider</button>
    </form>
</div>

 <!-- sca : ajout informations pour la changement de mot de passe  -->

 <div class="modal fade" id="response-message" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header modal-header-success">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h1><i class="glyphicon glyphicon-info-sign"></i> <div id="getMessage"></div></h1>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Fermer</button>
            </div>
        </div>
    </div>
</div>
<script src="/dist/js/sha512.js"></script>
<script src="/dist/js/profile.js"></script>
