<!-- Register Modal -->
<div class="modal fade" id="registerModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="waiting_like=false;">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h5 class="modal-title" id="registerModalLabel">Enregistrement</h5>
            </div>
            <div class="modal-body">
                <form id="formRegister" enctype="multipart/form-data">

                    <div class="form-group">
                        <label for="registerAvatar">Avatar</label>
                        <input type="file" name="avatar" id="avatar">
                    </div>
                    <input type="hidden" name="MAX_FILE_SIZE" value="1048576" />
                    <div class="form-group">
                        <label for="registerLastname">Nom *</label>
                        <input type="text" name="lastname" class="form-control" id="registerLastname" aria-describedby="emailHelp" placeholder="Votre nom" required>
                          <div class="alert alert-danger" id="nameMessage" style = "display:none"></div>
                    </div>
                    <div class="form-group">
                        <label for="registerFirstname">Prénom *</label>
                        <input type="text" name="firstname" class="form-control" id="registerFirstname" aria-describedby="emailHelp" placeholder="Votre prénom" required>
                        <div class="alert alert-danger" id="firstnameMessage" style = "display:none"></div>
                    </div>
                    <div class="form-group">
                        <label for="registerUsername">Nom d'utilisateur *</label>
                        <input type="text" name="username" class="form-control" id="registerUsername" aria-describedby="emailHelp" placeholder="Nom d'utilisateur" required>
                        <div class="alert alert-danger" id="usernameMessage" style = "display:none"></div>
                    </div>
                    <div class="form-group">
                        <label for="registerEmail">Email *</label>
                        <input type="text" name="email" class="form-control" id="registerEmail" aria-describedby="emailHelp" placeholder="Votre email" required>
                        <div class="alert alert-danger" id="mailMessage" style = "display:none"></div>
                    </div>
                    <div class="form-group">
                        <label for="registerPassword">Mot de passe *</label>
                        <input type="password" class="form-control" id="registerPassword" placeholder="Password">
                        <input type="hidden" name="password" class="form-control" id="registerEncodedPassword" placeholder="Votre mot de passe" required>
                        <div class="alert alert-danger" id="pwdMessage" style = "display:none"></div>
                    </div>
                    <div class="form-group">
                        <label for="registerPasswordConfirm">Mot de passe (confirmation) *</label>
                        <input type="password" class="form-control" id="registerPasswordConfirm" placeholder="Confirmer votre mot de passe" required>
                        <div class="alert alert-danger" id="cpwdMessage" style = "display:none"></div>
                    </div>

                    <div class="alert alert-danger" id="errorMessage" style = "display:none"></div>
                    <div class="alert alert-success" id="generalMessage" style = "display:none"></div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="buttonRegister">Inscription</button>
                <button type="button" id="buttonLoginSwitch" class="btn btn-secondary">J'ai un compte</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="waiting_like=false;">Fermer</button>
            </div>
        </div>
    </div>
</div>
 <!-- sca : création modal de réponse

 <div class="modal fade" id="response-message" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header modal-header-success">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h1><i class="glyphicon glyphicon-info-sign"></i> <div id="getMessage"></div></h1>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Fermer</button>
            </div>
        </div>
    </div>
</div>-->

<script src="/dist/js/register.js"></script>
