<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title><?php echo $title; ?></title>
        <link href="/dist/css/bootstrap.css" rel="stylesheet">
        <link href="/dist/font/css/font-awesome.min.css" rel="stylesheet">
        <link href="/dist/css/custom.css" rel="stylesheet">
        <!-- For perfomance issues, it would be better at the end. Anyway, it is easier if this include is here. -->
        <script src="/dist/js/jquery.min.js"></script>
    </head>
    <body>
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/accueil">CroWdFundin'</a>
                </div>
                <?php if(isset($_SESSION["user"])
                && !$_SESSION["user"]->getActive())
                {
                }
                else
                {
                ?>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li id="tab_home"><a href="/accueil">Accueil</a></li>
                        <li id="tab_create"><a <?php if( !isset($_SESSION["user"]) ){  echo 'data-toggle="modal" data-target="#loginModal" href="#"'; } else { echo 'href="/creer"';} ?>>Créer</a></li>
                        <li id="tab_idea"><a href="/idee">Idées</a></li>
                        <li id="tab_project"><a href="/projet">Projets</a></li>
                        <li id="tab_funded"><a href="/finance">Financés</a></li>
                        <li id="tab_rules"><a href="/charte">Charte</a></li>
                        <?php
                            if( isset($_SESSION["user"]) && ($_SESSION["user"]->getRole() == "ROLE_ADMIN" || $_SESSION["user"]->getRole() == "ROLE_MODO"))
                                require('views/partials/granted_nav.phtml');
                        ?>
                    </ul>
                    <!--sca 12 11 2017  : recherche par mot clé !-->
                    <div class="col-sm-3 col-md-3">
                        <form class="navbar-form" role="search" action="/">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Rechercher" name="keyword">
                            <div class="input-group-btn">
                                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                            </div>
                            </form>
                        </div>
                    </div>
                        <!-- fin sca !-->

                <?php
                     }
                ?>
                    <ul class="nav navbar-nav navbar-right">
                        <?php
                            if( isset($_SESSION["user"]) )
                                require('views/partials/connected_nav.phtml');
                            else
                                require('views/partials/not_connected_nav.phtml');
                        ?>
                    </ul>

                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
        <!-- Page Content -->
        <div class="container">
            <?php
                require("views/partials/".$template);
            ?>
            <?php
                if( !isset($_SESSION["user"]) ){
                    echo '<script src="/dist/js/sha512.js"></script>';
                    require('views/partials/user_login.phtml');
                    require('views/partials/user_register.phtml');
                }
                else{
                    echo '<script src="/dist/js/disconnect.js"></script>';
                }
            ?>
            <script src="/dist/js/bootstrap.min.js"></script>
            <script src="/dist/js/navigation.js"></script>
        </div>
        <footer class="footer" >
            <div class="text-center center-block">
                <a href="https://www.facebook.com/" target="_blank"><i id="social-fb" class="fa fa-facebook-square fa-3x social"></i></a>
                <a href="https://github.com/JeremyWau/integration_project" target="_blank"><i id="social-gp" class="fa fa-github-square fa-3x social"></i></a>
                <a href="https://twitter.com/?lang=fr" target="_blank"><i id="social-tw" class="fa fa-twitter-square fa-3x social"></i></a>
                <a href="mailto:crowdfundingwavre@gmail.com"><i id="social-em" class="fa fa-envelope-square fa-3x social"></i></a>
            </div>
        </footer>
    </body>
</html>
